export const kangyiSecondnavList = [
  {
    type: 'topic2',
    id: '7tPlDSzDgVk',
    thumbnail: 'https://x0.ifengimg.com/ucms/2021_32/3A324AEE3162A8FEF024DDA0E6E49C7AB6B1BD69_size11_w120_h120.png',
    imageList: [
      {
        url: 'https://x0.ifengimg.com/ucms/2021_32/3A324AEE3162A8FEF024DDA0E6E49C7AB6B1BD69_size11_w120_h120.png',
      },
    ],
    title: '国内疫情',
    subscribe: {
      followid: '',
      cateid: '',
      type: '',
      catename: '',
      originalName: '',
      cateSource: '',
      forbidFollow: '1',
      forbidJump: '1',
    },
    documentId: 'ucms_7tPlDSzDgVk',
    staticId: 'special_7tPlDSzDgVk',
    style: {
      view: 'titleimg',
      recomTag: {
        bg: '1',
        bgColor: '#26F54343',
        bgNightColor: '#26D33939',
        fontColor: '#FFF54343',
        fontNightColor: '#FFD33939',
        text: '专题',
        pos: '1',
      },
      feedbackreason: [
        {
          title: '不感兴趣',
          value: '0_不感兴趣',
        },
      ],
      defaultreason: '0_不感兴趣',
    },
    link: {
      type: 'web',
      url: 'https://news.ifeng.com/c/specialClient/7tPlDSzDgVk',
    },
    reftype: 'editor|ucms_7tPlDSzDgVk|||||%E8%B4%A2%E7%BB%8F-%E5%AE%8F%E8%A7%82%E7%BB%8F%E6%B5%8E|',
    intro: '',
    hasSlide: true,
    statisticTag: '',
  },
  {
    type: 'topic2',
    id: '7uLj4F83Cqm',
    thumbnail: 'https://x0.ifengimg.com/ucms/2021_32/ADEDC37F95249D02A74D251FFE45216C94BB04E5_size10_w120_h120.png',
    imageList: [
      {
        url: 'https://x0.ifengimg.com/ucms/2021_32/ADEDC37F95249D02A74D251FFE45216C94BB04E5_size10_w120_h120.png',
      },
    ],
    title: '全球疫情',
    subscribe: {
      followid: '',
      cateid: '',
      type: '',
      catename: '',
      originalName: '',
      cateSource: '',
      forbidFollow: '1',
      forbidJump: '1',
    },
    documentId: 'ucms_7uLj4F83Cqm',
    staticId: 'special_7uLj4F83Cqm',
    style: {
      view: 'titleimg',
      recomTag: {
        bg: '1',
        bgColor: '#26F54343',
        bgNightColor: '#26D33939',
        fontColor: '#FFF54343',
        fontNightColor: '#FFD33939',
        text: '专题',
        pos: '1',
      },
      feedbackreason: [
        {
          title: '不感兴趣',
          value: '0_不感兴趣',
        },
      ],
      defaultreason: '0_不感兴趣',
    },
    link: {
      type: 'web',
      url: 'https://news.ifeng.com/c/specialClient/7uLj4F83Cqm',
    },
    reftype: 'editor|ucms_7uLj4F83Cqm|||||%E5%85%B6%E4%BB%96|',
    intro: '',
    hasSlide: true,
    statisticTag: '',
  },
  {
    type: 'topic2',
    id: '7thiaab7wAK',
    thumbnail: 'https://x0.ifengimg.com/ucms/2021_32/E9FE8F99F174486D0F6AE64A25E7C5020BEC05DB_size9_w120_h120.png',
    imageList: [
      {
        url: 'https://x0.ifengimg.com/ucms/2021_32/E9FE8F99F174486D0F6AE64A25E7C5020BEC05DB_size9_w120_h120.png',
      },
    ],
    title: '输入疫情',
    subscribe: {
      followid: '',
      cateid: '',
      type: '',
      catename: '',
      originalName: '',
      cateSource: '',
      forbidFollow: '1',
      forbidJump: '1',
    },
    documentId: 'ucms_7thiaab7wAK',
    staticId: 'special_7thiaab7wAK',
    style: {
      view: 'titleimg',
      recomTag: {
        bg: '1',
        bgColor: '#26F54343',
        bgNightColor: '#26D33939',
        fontColor: '#FFF54343',
        fontNightColor: '#FFD33939',
        text: '专题',
        pos: '1',
      },
      feedbackreason: [
        {
          title: '不感兴趣',
          value: '0_不感兴趣',
        },
      ],
      defaultreason: '0_不感兴趣',
    },
    link: {
      type: 'web',
      url: 'https://news.ifeng.com/c/specialClient/7thiaab7wAK',
    },
    reftype: 'editor|ucms_7thiaab7wAK|||||%E5%85%B6%E4%BB%96|',
    intro: '',
    hasSlide: true,
    statisticTag: '',
  },
  {
    type: 'web',
    id: 'https://news.ifeng.com/c/specialClient/7uGaH6JaA1A?needpage=1&webkit=1&prov=029',
    thumbnail: 'http://x0.ifengimg.com/cmpp/2020/0226/d2170fad2d6e978size11_w120_h120.png',
    imageList: [
      {
        url: 'http://x0.ifengimg.com/cmpp/2020/0226/d2170fad2d6e978size11_w120_h120.png',
      },
    ],
    title: '陕西疫情',
    subscribe: {
      followid: '',
      cateid: '',
      type: '',
      catename: '',
      originalName: '',
      cateSource: '',
      forbidFollow: '1',
      forbidJump: '1',
    },
    documentId: 'ucms_https://news.ifeng.com/c/specialClient/7uGaH6JaA1A?needpage=1&webkit=1&prov=029',
    staticId: 'https://news.ifeng.com/c/specialClient/7uGaH6JaA1A?needpage=1&webkit=1&prov=029',
    style: {
      view: 'titleimg',
      feedbackreason: [
        {
          title: '不感兴趣',
          value: '0_不感兴趣',
        },
      ],
      defaultreason: '0_不感兴趣',
    },
    link: {
      type: 'web',
      url: 'https://news.ifeng.com/c/specialClient/7uGaH6JaA1A?needpage=1&webkit=1&prov=029',
      weburl: 'https://news.ifeng.com/c/specialClient/7uGaH6JaA1A?needpage=1&webkit=1&prov=029',
      backendStaticId: 'https://news.ifeng.com/c/specialClient/7uGaH6JaA1A?needpage=1&webkit=1&prov=029',
      staticId: 'https://news.ifeng.com/c/specialClient/7uGaH6JaA1A?needpage=1&webkit=1&prov=029',
    },
    reftype: 'editor|||||||',
    intro: '',
    hasSlide: true,
    statisticTag: '',
  },
  {
    type: 'topic2',
    id: '85mhVvWS5i4',
    thumbnail: 'https://x0.ifengimg.com/ucms/2021_32/B409B0423CCEE00002B8DB4B02CC57F4ADF29704_size9_w120_h120.png',
    imageList: [
      {
        url: 'https://x0.ifengimg.com/ucms/2021_32/B409B0423CCEE00002B8DB4B02CC57F4ADF29704_size9_w120_h120.png',
      },
    ],
    title: '接种进度',
    subscribe: {
      followid: '',
      cateid: '',
      type: '',
      catename: '',
      originalName: '',
      cateSource: '',
      forbidFollow: '1',
      forbidJump: '1',
    },
    documentId: 'ucms_85mhVvWS5i4',
    staticId: 'special_85mhVvWS5i4',
    style: {
      view: 'titleimg',
      recomTag: {
        bg: '1',
        bgColor: '#26F54343',
        bgNightColor: '#26D33939',
        fontColor: '#FFF54343',
        fontNightColor: '#FFD33939',
        text: '专题',
        pos: '1',
      },
      feedbackreason: [
        {
          title: '不感兴趣',
          value: '0_不感兴趣',
        },
      ],
      defaultreason: '0_不感兴趣',
    },
    link: {
      type: 'web',
      url: 'https://news.ifeng.com/c/specialClient/85mhVvWS5i4',
    },
    reftype: 'editor|ucms_85mhVvWS5i4||||||',
    intro: '',
    hasSlide: true,
    statisticTag: '',
  },
];
