export const defaultCategories = [
  { name: '关注', api: '', id: 'guanzhu', index: '0' },
  { name: '头条', api: '', id: 'toutiao', index: '1' },
  { name: '视频', api: '', id: 'shipin', index: '2' },
  { name: '抗疫', api: '', id: 'kangyi', index: '3' },
  { name: '西安', api: '', id: 'xian', index: '4' },
  { name: '财经', api: '', id: 'caijing', index: '5' },
  { name: '娱乐', api: '', id: 'yule', index: '6' },
  { name: '军事', api: '', id: 'junshi', index: '7' },
  { name: '君品谈', api: '', id: 'junpintan', index: '8' },
  { name: '小视频', api: '', id: 'xiaoshipin', index: '9' },
  { name: '影视剧', api: '', id: 'yingshiju', index: '10' },
  { name: '新时代', api: '', id: 'xinshidai', index: '11' },
  { name: '舍得人物', api: '', id: 'shederenwu', index: '12' },
  { name: '东京奥运', api: '', id: 'dongjingaoyun', index: '13' },
  { name: '冬奥', api: '', id: 'dongao', index: '14' },
  { name: '要闻', api: '', id: 'yaowen', index: '15' },
  { name: '文创', api: '', id: 'wenchuang', index: '16' },
  { name: '科技', api: '', id: 'keji', index: '17' },
  { name: '美食', api: '', id: 'meishi', index: '18' },
  { name: '教育', api: '', id: 'jiaoyu', index: '19' },
  { name: 'FUN来了', api: '', id: 'FUNlaile', index: '20' },
  { name: '5G', api: '', id: '5G', index: '21' },
  { name: '推荐', api: '', id: 'tuijian', index: '22' },
  { name: '体育', api: '', id: 'tiyu', index: '23' },
  { name: '历史', api: '', id: 'lishi', index: '24' },
  { name: '小说', api: '', id: 'xiaoshuo', index: '25' },
  { name: '汽车', api: '', id: 'qiche', index: '26' },
  { name: '房产', api: '', id: 'fangchan', index: '27' },
  { name: '台湾', api: '', id: 'taiwan', index: '28' },
  { name: '暖新闻', api: '', id: 'nuanxinwen', index: '29' },
  { name: '国际', api: '', id: 'guoji', index: '30' },
  { name: '健康', api: '', id: 'jiankang', index: '31' },
  { name: '时尚', api: '', id: 'shishang', index: '32' },
  { name: '青春BANG', api: '', id: 'qingchunBANG', index: '33' },
  { name: '电商研究院', api: '', id: 'dianshangyanjiuyuan', index: '34' },
  { name: '旅游', api: '', id: 'lvyou', index: '35' },
  { name: '佛教', api: '', id: 'fojiao', index: '36' },
  { name: '原创', api: '', id: 'yuanchuang', index: '37' },
  { name: '炒股大赛', api: '', id: 'chaogudasai', index: '38' },
  { name: '风直播', api: '', id: 'fengzhibo', index: '39' },
  { name: '香港', api: '', id: 'xianggang', index: '40' },
];
export const bakCategories = [
  { name: '航天', api: '', id: 'hangtian', index: '41' },
  { name: '区块链', api: '', id: 'qukuailian', index: '42' },
  { name: '扶贫', api: '', id: 'fupin', index: '43' },
  { name: '热播', api: '', id: 'rebo', index: '44' },
  { name: '精选', api: '', id: 'jingxuan', index: '45' },
  { name: '港股', api: '', id: 'ganggu', index: '46' },
  { name: '音乐', api: '', id: 'yinle', index: '47' },
  { name: '政务', api: '', id: 'zhengwu', index: '48' },
  { name: '数码', api: '', id: 'shuma', index: '49' },
  { name: '文化', api: '', id: 'wenhua', index: '50' },
  { name: '读书', api: '', id: 'dushu', index: '51' },
  { name: '星座', api: '', id: 'xingzuo', index: '52' },
  { name: '评论', api: '', id: 'pinglun', index: '53' },
  { name: '电影', api: '', id: 'dianying', index: '54' },
  { name: '酒业', api: '', id: 'jiuye', index: '55' },
  { name: '品牌主场', api: '', id: 'pinpaizhuchang', index: '56' },
  { name: '国学', api: '', id: 'guoxue', index: '57' },
  { name: '公益', api: '', id: 'gongyi', index: '58' },
  { name: '家居', api: '', id: 'jiaju', index: '59' },
  { name: '智库', api: '', id: 'zhiku', index: '60' },
  { name: '政能量', api: '', id: 'zhengnengliang', index: '61' },
  { name: '科技城', api: '', id: 'kejicheng', index: '62' },
  { name: '加拿大', api: '', id: 'jianada', index: '63' },
  { name: '创新', api: '', id: 'chuangxin', index: '64' },
];
export const allCategories = [...defaultCategories, ...bakCategories];
const _defaultCategoriesNames = [];
for (let item of defaultCategories) {
  _defaultCategoriesNames.push(item.name);
}
export const defaultCategoriesNames = _defaultCategoriesNames;
