name: Deploy to Server

on:
  push:
    branches: [proxy]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: proxy

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"

      - name: Install dependencies
        run: yarn

      - name: Build Astro project
        run: yarn build

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 删除旧目录（如果存在）
            rm -rf /root/ifeng-proxy
            
            # 创建新目录
            mkdir -p /root/ifeng-proxy
            
            # 复制文件到新目录
            cp -r dist/* /root/ifeng-proxy/
            cp package.json /root/ifeng-proxy/
            cp -r node_modules /root/ifeng-proxy/
            
            # 进入目录并启动服务
            cd /root/ifeng-proxy
            npm run pm2